name: GitHub Environments

on:
  workflow_dispatch:



jobs:
  deployment:
    
    runs-on: ubuntu-latest
    environment: 
      name: production  #name of environment to which we wantto deploy our workflow
      url: https://github.com
      
      
    steps:
      - name: 'Print secret from environment'
        run: |
            echo "APP_SECRET: ${{ secrets.APP_SECRET  }}"