name: 'Custom Env Vars'

on:
  workflow_dispatch:
  
env:
  DAY_OF_WEEK: Funday
  testvar: value-1
  

jobs: 
  mainjob:
    name: 'Print the env vars'
    runs-on: ubuntu-latest

    env:
      Greeting: Dear
      testvar: value-2    #if remove this ,value-1
    
    steps:
    - name: print-values-of-env-vars
      run: |
        echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"   #custom variables 
        echo "testvar  $testvar"
        echo "testvar  ${{ env.testvar }}"
      env:
          First_Name: Student
          testvar: value-3  #if remove this ,it will take job level value(value-2)